---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/tag.platform-website: regex:^sha-*
  name: platform-website
  namespace: platform-website
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: platform-website
      containers:
        - image: devlaunchers/platform-website:sha-e2bd651
          name: platform-website
          env:
            - name: GOOGLE_AUTH_URL
              value: "https://api-staging.devlaunchers.com/auth/google"
            - name: DISCORD_AUTH_URL
              value: "https://discord.com/api/oauth2/authorize?client_id=815294711983112194&redirect_uri=https%3A%2F%2Fapi-staging.devlaunchers.com%2Fusers%2Fauth%2Fdiscord%2Fcallback&response_type=code&scope=identify"
