---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/tag.platform-website: regex:^sha-*
  name: platform-website
  namespace: platform-website
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: platform-website
      containers:
      - image: devlaunchers/platform-website:sha-ca4f2b9
        name: platform-website
