apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-website
bases:
- ../workload
- wordpress.yaml
images:
- name: devlaunchers/platform-website:d0d8327-202105311801 # {"$imagepolicy": "platform-website:platform-website"}
  newName: devlaunchers/platform-website
  newTag: d0d8327-202105311801
