language: node_js
node_js:
  - "11.6.0"
cache:
  directories:
  - node_modules
script:
  #- npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master

after_failure:
  - cat /home/travis/.npm/_logs/*-debug.log