# https://github.com/flareact/flareact-site/blob/master/docs/deployment.md
name: Staging Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - flux-patch.yaml
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: devlaunchers/platform-website
          tag_with_ref: true
          tag_with_sha: true
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build
        env:
          CI: false
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{secrets.CF_API_TOKEN}}
          environment: staging
        env:
          # https://github.com/cloudflare/wrangler-action/issues/12
          USER: root