name: staging
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy to staging hostname
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build
        env:
          CI: false
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - names: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{secrets.CF_API_TOKEN}}
          environment: staging